### ISSUE TITLE
library(NISTUnits) issue

### ISSUE THREAD

**Issue by pkrishn9jj88g** [MicrosoftLearning/Essential-Math-R#8]
I am doing this course in edX and while running the 1st notebook in module 3, i get the following message in Azure. 

library(NISTunits)
Error in library(NISTunits): there is no package called ‘NISTunits’

**Comment by StephenElston** [comment]
I suggest you try adding a code cell before this one.   

install.packages('NISTunits')

**Comment by pkrishn9jj88g** [comment]
Thank you that worked

**Comment by StephenElston** [comment]
Good! I am closing this issue.
